# Generated by Django 5.1.1 on 2026-05-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.projectrole', verbose_name='Роль проекта'),
        ),
        migrations.AddField(
            model_name='projectroleskill',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='projects.projectrole', verbose_name='Роль проекта'),
        ),
        migrations.AddField(
            model_name='projectroleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_role_requirements', to='users.skill', verbose_name='Навык'),
        ),
        migrations.AddField(
            model_name='roleinterest',
            name='project_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='projects.projectrole', verbose_name='Роль проекта'),
        ),
        migrations.AddField(
            model_name='roleinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_interests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role_interest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membership', to='projects.roleinterest', verbose_name='Заявка/приглашение'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='projects.field', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_roles', to='projects.specialization', verbose_name='Специализация'),
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(fields=('project_role', 'skill'), name='unique_project_role_skill'),
        ),
        migrations.AddConstraint(
            model_name='projectroleskill',
            constraint=models.UniqueConstraint(fields=('project_role', 'order'), name='unique_project_role_skill_order'),
        ),
        migrations.AddConstraint(
            model_name='roleinterest',
            constraint=models.UniqueConstraint(fields=('user', 'project_role'), name='unique_user_project_role_interest'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project_role',), name='unique_active_membership_per_project_role'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.UniqueConstraint(fields=('field', 'name'), name='unique_specialization_per_field'),
        ),
    ]
