# Generated by Django 5.1.1 on 2026-06-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrole',
            name='is_open',
        ),
        migrations.AddField(
            model_name='field',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок на главной'),
        ),
        migrations.AddField(
            model_name='field',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок на главной'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать в подборке'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('project', 'specialization'), name='unique_project_role_specialization'),
        ),
    ]
