# Generated by Django 5.1.1 on 2026-08-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectrole_is_open_field_featured_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmembership',
            name='unique_active_membership_per_project_role',
        ),
    ]
