# Generated by Django 5.1.1 on 2026-05-29 12:10

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='Юзернейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('account_type', models.CharField(choices=[('participant', 'Участник'), ('owner', 'Владелец')], max_length=20, verbose_name='Тип аккаунта')),
                ('level', models.CharField(blank=True, choices=[('junior', 'Базовый'), ('middle', 'Средний'), ('senior', 'Продвинутый')], max_length=20, null=True, verbose_name='Уровень')),
                ('workload_hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Количество рабочих часов в неделю')),
                ('work_format', models.CharField(blank=True, choices=[('remote', 'Удалённо'), ('hybrid', 'Гибрид')], max_length=20, null=True, verbose_name='Формат работы')),
                ('employment_type', models.CharField(blank=True, choices=[('combined', 'Совмещаю'), ('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость')], max_length=20, null=True, verbose_name='Тип занятости')),
                ('search_status', models.CharField(blank=True, choices=[('looking_for_team', 'Ищу команду'), ('looking_for_members', 'Ищу участников'), ('not_looking', 'Не ищу')], max_length=20, null=True, verbose_name='Статус поиска')),
                ('profile_visibility', models.CharField(choices=[('public', 'Публичный'), ('matched_only', 'Только метчи'), ('hidden', 'Скрытый')], default='public', max_length=20, verbose_name='Видимость профиля')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='Социальные сети')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='projects.specialization', verbose_name='Специализация')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта портфолио')),
                ('task', models.TextField(blank=True, max_length=255, null=True, verbose_name='Задача')),
                ('solution', models.TextField(blank=True, max_length=255, null=True, verbose_name='Решение')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/', verbose_name='Изображение работы портфолио')),
                ('technologies', models.JSONField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_works', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Работа портфолио',
                'verbose_name_plural': 'Работы портфолио',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный проект',
                'verbose_name_plural': 'Избранные проекты',
                'ordering': ('user', 'project'),
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_user_favorite_project')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('middle', 'Middle'), ('advanced', 'Advanced')], max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.skill', verbose_name='Навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Навыки пользователя',
                'verbose_name_plural': 'Навыки пользователей',
                'ordering': ('user', 'skill'),
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill')],
            },
        ),
    ]
