# Generated by Django 5.1.1 on 2026-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_notifications_enabled_user_notification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
    ]
