# Generated by Django 5.1.1 on 2026-06-30 16:45

from django.db import migrations, models


def fill_skill_slugs(apps, schema_editor):
    Skill = apps.get_model('users', 'Skill')

    for skill in Skill.objects.all().order_by('id'):
        if not skill.slug:
            skill.slug = f'skill-{skill.id}'
            skill.save(update_fields=('slug',))


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectrole_is_open_field_featured_order_and_more'),
        ('users', '0003_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='fields',
            field=models.ManyToManyField(related_name='skills', to='projects.field', verbose_name='Области'),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Слаг'),
        ),
        migrations.RunPython(
            fill_skill_slugs,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
